title:       "Operating Systems 2021-1 (OS211)"
version:     "0030---05-Mar-2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Annisa Dian Nugrahani"
address:          "Depok"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://nisadn.github.io/ostes/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/nisadn/ostes/"
urlghpage:        "https://nisadn.github.io/ostes/"
keywords:         "jekyll, testing"
github:           [metadata]

